### ISSUE TITLE
each() deprecated in php 7.2

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_tags#1]
I get the following tag error notice on php 7.2:

```
Tag error: <txp:smd_tag_list parent='<txp:variable name="tag_language" />' wraptag="" break="">
<li><a href="<txp:site_url /><txp:variable name="tag_language" />/<txp:if_variable name="tag_language" value="referenzen">thema<txp:else/>topic</txp:if_variable>/<txp:smd_tag_name title="0" link="0" />"><txp:smd_tag_name title="1" link="0" /></a></li></txp:smd_tag_list> -> 8192: The each() function is deprecated. This message will be suppressed on further calls while parsing form reference_list_item on page references
```

I think it's referring to [this line](https://github.com/Bloke/smd_tags/blob/master/smd_tags.php#L4375). 

Might changing:

```
while (list($key, $row) = each($rs)) {
```
to:
```
foreach ($rs as $key => $row) {
```
resolve the error?

**Comment by Bloke** [comment]
Dammit, yes, that patch should fix it. If you fancy proposing a PR I'll merge it straight away. If not I'll get to it as soon as I can. Thanks.

**Comment by jools-r** [comment]
I'll do some more checks first as I'm not getting the correct tag filtering behaviour at the moment, though this should not affect that.

**Comment by jools-r** [comment]
Thanks! Tag lists being created without errors...
