### ISSUE TITLE
if_first and if_last of type not recognised

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_tags#13]
When passing smd_related_tags to a form like this:

```
<txp:smd_related_tags section="news" type="article" wraptag="" break="" form="detail_listitem" />
```

… the `if_first_article` and `if_last_article` containers in the linked form are not processed.

### Home diagnosis

As far as I can tell, this is because the `{content-type}['is_first']` and `{content-type}['is_last']` array keys are not set by the plugin like they are in [txplib_publish.php](https://github.com/textpattern/textpattern/blob/1ce1250be24d096d37ad25cd46a0796c7ce42a9f/textpattern/lib/txplib_publish.php#L1305-L1306), and these are the triggers for the [if_first / if_last](https://github.com/textpattern/textpattern/blob/1ce1250be24d096d37ad25cd46a0796c7ce42a9f/textpattern/publish/taghandlers.php#L3079) functions.

Replicating the same pattern in the `smd_related_tags` function of the plugin seems to produce the desired result for articles, e.g. adding a counter and setting the array keys in [this code block](https://github.com/Bloke/smd_tags/blob/1960f75925abe1a19d3fc79f90438c8c072c9828/smd_tags.php#L4370-L4379). The function already saves the total matches in `$contentCount`.

```
$itemCount = 0;

foreach ($rs as $row) {
    if (!in_array($row['ID'], $uniqrs)) {
        $itemCount++;
        $safe = ($thisarticle) ? $thisarticle : NULL;
        $thisarticle['is_first'] = ($itemCount == 1);
        $thisarticle['is_last'] = ($itemCount == $contentCount);
        populateArticleData($row);
        $row['Title'] = ($no_widow) ? noWidow(escape_title($row['Title'])) : escape_title($row['Title']);
        $out[] = ($form) ? parse_form($form) : (($thing) ? parse($thing) : href($row['Title'], permlinkurl($row)));
        $uniqrs[] = $row['ID'];
        $thisarticle = $safe;

    }
}
```

Analog for the cases “image”, “file” and “link”. 

Is that all it needs?

**Comment by Bloke** [comment]
Ooft, good catch. Yes, I expect it just needs those entries adding for each content type. I'm now wondering how (or if) it ever worked... :|

Do you want me to patch it now or are you okay to make a cheeky PR?

Thank you.

**Comment by jools-r** [comment]
Here you go: https://github.com/Bloke/smd_tags/pull/14

**Comment by jools-r** [comment]
Thank you!!
